### ISSUE TITLE
[Feature] 1.20 支持

### ISSUE THREAD

**Issue by Adogs1** [AnzhiZhang/MCDRCommandFabric#6]
请开发者大大添加对1.20.2支持，谢谢

**Comment by AnzhiZhang** [comment]
PR is welcomed

**Comment by Adogs1** [comment]
> 欢迎公关

无法完成？

**Comment by Adogs1** [comment]
> 请开发者大大添加对1.20.2支持，谢谢

能快点更新吗？或者可以更改版本号实现1.20.2？

**Comment by AnzhiZhang** [comment]
1.20 已更新，发布平台审核完成后我会在此更新通知

**Comment by Adogs1** [comment]
> 1.20 已更新，发布平台审核完成后我会在此更新通知

谢谢！

**Comment by Adogs1** [comment]
> 1.20 已更新，发布平台审核完成后我会在此更新通知

如果能教会我怎么构建，我可以以后帮助更进Minecraft版本更新！！！

**Comment by Adogs1** [comment]
> 1.20 已更新，发布平台审核完成后我会在此更新通知

在1.20.2服务端上报错：
[23:44:06] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.3
[23:44:06] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[23:44:06] [ForkJoinPool-1-worker-8/WARN]: Mod mcdrcommand uses the version v1.2.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:44:06] [main/WARN]: Mod resolution failed
[23:44:06] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED mcdrcommand v1.2.0 {depends minecraft @ [~1.20.4]}, ROOT_FORCELOAD_SINGLE mcdrcommand v1.2.0]
[23:44:06] [main/INFO]: Reason: [HARD_DEP mcdrcommand v1.2.0 {depends minecraft @ [~1.20.4]}, HARD_DEP magiclib-1_14_4 0.7.387+c02a0de-stable {depends minecraft @ [1.14.x]}, HARD_DEP magiclib-1_15_2 0.7.387+c02a0de-stable {depends minecraft @ [1.15.x]}, HARD_DEP magiclib-1_16_5 0.7.387+c02a0de-stable {depends minecraft @ [1.16.x]}, HARD_DEP magiclib-1_17_1 0.7.387+c02a0de-stable {depends minecraft @ [1.17.x]}, HARD_DEP magiclib-1_18_2 0.7.387+c02a0de-stable {depends minecraft @ [1.18.x]}, HARD_DEP magiclib-1_19_2 0.7.387+c02a0de-stable {depends minecraft @ [1.19.2]}, HARD_DEP magiclib-1_19_3 0.7.387+c02a0de-stable {depends minecraft @ [1.19.3]}, HARD_DEP magiclib-1_19_4 0.7.387+c02a0de-stable {depends minecraft @ [1.19.4]}, HARD_DEP magiclib-1_20_1 0.7.387+c02a0de-stable {depends minecraft @ [>1.20 <=1.20.1]}]
[23:44:06] [main/INFO]: SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, malilib, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, litematica, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, ommc-1_20_2, fabric-models-v0, fabric-sound-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1]
[23:44:06] [main/INFO]: Fix: add [], remove [], replace [[mcdrcommand v1.2.0] -> add:mcdrcommand 1 ([(-∞,∞)])]
[23:44:06] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MCDRCommand' (mcdrcommand) v1.2.0 with any version that is compatible with:
		 - minecraft 1.20.2
More details:
	 - Mod 'MCDRCommand' (mcdrcommand) v1.2.0 requires any version between 1.20.4 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.7.387+c02a0de-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.7.387+c02a0de-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.7.387+c02a0de-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.7.387+c02a0de-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.7.387+c02a0de-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.19.2' (magiclib-1_19_2) 0.7.387+c02a0de-stable requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.19.3' (magiclib-1_19_3) 0.7.387+c02a0de-stable requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.19.4' (magiclib-1_19_4) 0.7.387+c02a0de-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	 - Mod 'MagicLib for 1.20.1' (magiclib-1_20_1) 0.7.387+c02a0de-stable requires any version between 1.20 (exclusive) and 1.20.1 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]

**Comment by AnzhiZhang** [comment]
https://modrinth.com/mod/mcdr-command-fabric/version/v1.2.1-1.20.4
